name: Test

on:
  push:
    branches-ignore: [ "main" ]

env:
  NODE_VERSION: ">=18.18.0"
  SKIP_ENV_VALIDATION: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          working-directory: ./website
      - name: Install Dependencies
        run: |
          bun install --frozen-lockfile
        working-directory: ./website
      - name: Validate Build
        run: bun run build
        working-directory: ./website
